---
# Check if nginx is installed
- name: Install nginx using apt
  apt:
    name: nginx
    state: latest
  notify: restart
  tags:
  - setup

- name: Copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ app_name }}
  notify: restart
  tags:
    - setup