---
- name: Install docker
  hosts: app_server_python
  roles:
    - role: docker
      become: true

- name: Deploy web app
  hosts: app_server_python
  roles: 
  - role: web_app
    become: true
    vars:
      app_name: "app_python"
      app_port: 5000
      app_dir: "/home/{{ ansible_user }}/{{ app_name }}"
      host_name: "{{ ansible_host }}"
      web_app_full_wipe: true
